// ACTION TYPES
export const SAVE_KEY = 'sfm/Dashboard/SAVE_KEY';
export const CREATE_NEW_SPREADSHEET = 'sfm/Dashboard/CREATE_NEW_SPREADSHEET';
export const ON_SYNC_LOCAL_CACHE = 'sfm/Dashboard/ON_SYNC_LOCAL_CACHE';
export const CREATE_SHEET_FROM_GENERIC_TEMPLATE =
  'sfm/Dashboard/CREATE_SHEET_FROM_GENERIC_TEMPLATE';
export const CREATE_SHEET_FROM_PREVIOUS_MONTH =
  'sfm/Dashboard/CREATE_SHEET_FROM_PREVIOUS_MONTH';
export const TRY_SYNC_AGAIN = 'sfm/Dashboard/TRY_SYNC_AGAIN';

// OTHER
export const ACTIONABLE_DIALOG_NO_SHEETS = 'ACTIONABLE_DIALOG_NO_SHEETS';
export const ACTIONABLE_DIALOG_PREVIOUS_MONTH_SHEET =
  'ACTIONABLE_DIALOG_PREVIOUS_MONTH_SHEET';
